server:
  port: 8081

#配置rabbitmq服务
spring:
  rabbitmq:
    host: 192.168.3.17
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true